version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'smartlock'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user1'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'User1@312'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'User1@312'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql